channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake =5.5.4
  - python =3.6
  - jinja2 =2.10
  - networkx =2.1
  - matplotlib =2.2.3
  - graphviz =2.38.0
  - pygraphviz =1.3.1
  - pysam =0.15.0
